### ISSUE TITLE
Separate package for mcfunction

### ISSUE THREAD

**Issue by SebastianSpeitel** [throw-out-error/minecraft-datapack#5]
Hi,

i noticed you started typing the minecraft commands (e.g. selector). I believe it could be beneficial to exclude all this into an external package so someone can use it outside of this package.

Do you have any communication channel where something like this could be discussed?

Greetings
Sebastian

**Comment by Brent-Trenholme** [comment]
Well, we do have a discord server if that is the sort of thing that you're implying by "communication channel". I would definitely consider doing something like that.

**Comment by SebastianSpeitel** [comment]
Could you send me an invite link?

**Comment by Brent-Trenholme** [comment]
https://discord.gg/uApHFz4
